/* Generated by the Nim Compiler v1.7.1 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;

function HEX3Aanonymous_503316519() {
    
function HEX3Aanonymous_503316520() {
        print("Hello");

      
    }

    vim.api.nvim_buf_create_user_command(0, "Wazeee", HEX3Aanonymous_503316520, {});

  
}
export let setup = HEX3Aanonymous_503316519;
